// entrypoints/bookmark/App.tsx
import React, { useState, useEffect, useRef } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { BookmarkTree } from '../../components/BookmarkTree';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../../components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '../../components/ui/alert-dialog';
import { useToast } from '../../components/ui/use-toast';
import { getMessage } from '../../utils/i18n';
import type { BookmarkMenuNode } from '../../libs/BookmarkLib';
import { Edit, Trash2, Folder, Tag, X } from 'lucide-react';
import type { Bookmark } from '../../store';

interface BookmarkItem extends chrome.bookmarks.BookmarkTreeNode {
  url?: string | null;
}

export default function App() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const { toast } = useToast();
  const [menu, setMenu] = useState<BookmarkMenuNode[]>([]);
  const [loading, setLoading] = useState(false);
  const [height, setHeight] = useState(0);
  const [pid, setPid] = useState('0');
  const [bid, setBid] = useState('0');
  const [bookmarks, setBookmarks] = useState<BookmarkItem[] | null>(null);
  const [search, setSearch] = useState<string | null>(null);
  const [breadcrumb, setBreadcrumb] = useState<chrome.bookmarks.BookmarkTreeNode[]>([]);
  const [saving, setSaving] = useState(false);
  const [dialogFormVisible, setDialogFormVisible] = useState(false);
  const [dialogAddFolderFormVisible, setDialogAddFolderFormVisible] = useState(false);
  const [bookmarkData, setBookmarkData] = useState<{
    id: string | null;
    title: string | null;
    url: string | null;
  }>({
    id: null,
    title: null,
    url: null,
  });
  const [menuSelector, setMenuSelector] = useState<{ id: string; label: string } | null>(null);
  const [bookmarkFolder, setBookmarkFolder] = useState<{
    parentId: string | null;
    title: string | null;
  }>({
    parentId: null,
    title: null,
  });
  const [removeDialogOpen, setRemoveDialogOpen] = useState(false);
  const [itemToRemove, setItemToRemove] = useState<BookmarkItem | null>(null);
  const [selectedMenuId, setSelectedMenuId] = useState('0');
  const topRef = useRef<HTMLDivElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    document.title = getMessage('appname');
    const queryPid = searchParams.get('pid') || '0';
    const queryBid = searchParams.get('bid') || '0';
    setPid(queryPid);
    setBid(queryBid);
    getBookmarkMenu();
  }, [searchParams]);

  useEffect(() => {
    if (topRef.current) {
      const totalHeight = document.body.offsetHeight;
      const topHeight = topRef.current.offsetHeight;
      setHeight(totalHeight - topHeight);
    }
  }, [bookmarks, menu]);

  useEffect(() => {
    if (pid) {
      getBookmarkChildren(pid);
      setSelectedMenuId(pid);
    }
  }, [pid]);

  useEffect(() => {
    if (bid && bid !== '0') {
      setSearch(bid);
    } else {
      setSearch(null);
    }
  }, [bid]);

  const getBookmarkMenu = () => {
    setLoading(true);
    chrome.runtime.sendMessage(
      { ctype: 'getbookmark_menu', cdata: false },
      (response) => {
        if (response && response.cdata) {
          setMenu(response.cdata);
          setLoading(false);
          if (pid) {
            getBookmarkChildren(pid);
          }
        }
      }
    );
  };

  const getBookmarkChildren = (id: string) => {
    const targetId = id === '0' ? '0' : id;
    chrome.runtime.sendMessage(
      { ctype: 'getbookmark_children', cdata: targetId },
      (response) => {
        if (response && response.cdata) {
          const items: BookmarkItem[] = response.cdata.map((item: chrome.bookmarks.BookmarkTreeNode) => ({
            ...item,
            url: item.url || null,
          }));
          setBookmarks(items);
          if (bid && bid !== '0') {
            setSearch(bid);
          }
          getBreadcrumb(targetId);
        }
      }
    );
  };

  const getBreadcrumb = (id: string) => {
    if (id === '0') {
      setBreadcrumb([]);
      return;
    }
    chrome.runtime.sendMessage(
      { ctype: 'getbookmark_breadcrumb', cdata: id },
      (response) => {
        if (response && response.cdata) {
          setBreadcrumb(response.cdata);
        }
      }
    );
  };

  const handleNodeClick = (node: BookmarkMenuNode) => {
    if (node.id === '0') {
      navigate('/?pid=0');
    } else {
      navigate(`/?pid=${node.id}`);
    }
  };

  const handleVisit = (item: BookmarkItem) => {
    if (item.url) {
      window.open(item.url);
    } else {
      navigate(`/?pid=${item.id}`);
    }
  };

  const handleEdit = (item: BookmarkItem) => {
    chrome.runtime.sendMessage(
      { ctype: 'getbookmark_byid', cdata: { id: item.id, action: 'edit_open' } },
      (response) => {
        if (response && response.cdata && response.cdata.bookmark) {
          const bookmark = response.cdata.bookmark;
          setBookmarkData({
            id: bookmark.id,
            title: bookmark.title,
            url: bookmark.url || null,
          });
          if (bookmark.parent) {
            setMenuSelector({
              id: bookmark.parent.id,
              label: bookmark.parent.title,
            });
          }
          setDialogFormVisible(true);
        }
      }
    );
  };

  const handleRemove = (item: BookmarkItem) => {
    setItemToRemove(item);
    setRemoveDialogOpen(true);
  };

  const confirmRemove = () => {
    if (!itemToRemove) return;
    chrome.runtime.sendMessage(
      { ctype: 'remove_bookmark', cdata: itemToRemove },
      (response) => {
        if (response && response.cdata) {
          toast({
            variant: 'success',
            title: getMessage('success'),
          });
          getBookmarkChildren(pid);
        }
      }
    );
    setRemoveDialogOpen(false);
    setItemToRemove(null);
  };

  const handleCancelDialog = () => {
    if (saving) return;
    setDialogFormVisible(false);
    setBookmarkData({ id: null, title: null, url: null });
    setMenuSelector(null);
  };

  const handleConfirmDialog = () => {
    if (!bookmarkData.id) return;
    setSaving(true);
    chrome.runtime.sendMessage(
      {
        ctype: 'update_bookmark',
        cdata: {
          id: bookmarkData.id,
          title: bookmarkData.title,
          url: bookmarkData.url,
          parentId: menuSelector?.id || null,
          index: 0,
        },
      },
      (response) => {
        if (response && response.cdata) {
          toast({
            variant: 'success',
            title: getMessage('success'),
          });
          getBookmarkMenu();
          setMenuSelector(null);
          setSaving(false);
          setDialogFormVisible(false);
        }
      }
    );
  };

  const handleOpenCreateFolder = () => {
    setBookmarkFolder({ parentId: pid, title: null });
    setDialogAddFolderFormVisible(true);
  };

  const handleCreateFolder = () => {
    if (!bookmarkFolder.title) return;
    chrome.runtime.sendMessage(
      { ctype: 'create_bookmark_folder', cdata: bookmarkFolder },
      (response) => {
        if (response && response.cdata) {
          toast({
            variant: 'success',
            title: getMessage('success'),
          });
          getBookmarkMenu();
          setDialogAddFolderFormVisible(false);
          setBookmarkFolder({ parentId: null, title: null });
        }
      }
    );
  };

  const handleFormNodeClick = (node: BookmarkMenuNode) => {
    setMenuSelector({ id: node.id, label: node.label });
  };

  const filteredBookmarks = bookmarks?.filter(
    (item) => !search || item.id.includes(search)
  ) || [];

  return (
    <div className="h-screen flex flex-col">
      <div
        ref={topRef}
        className="bg-primary text-white pt-2"
      >
        <div className="flex items-center justify-between px-10">
          <div className="text-[22px] font-extrabold pt-2 pl-10">
            {getMessage('appname')}
          </div>
          <div className="flex gap-4 pt-2.5 text-right">
            <a
              href="https://akawa.ink/donate"
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-white hover:underline"
            >
              {getMessage('donate')}
            </a>
            <a
              href="https://github.com/ety001/bookmark-extension"
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-white hover:underline"
            >
              {getMessage('source_code')}
            </a>
            {/* TODO: 推广页面已不存在，暂时注释掉 */}
            {/* <a
              href="https://creatorsdaily.com/9999e88d-0b00-46dc-8ff1-e1d311695324#comments"
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-white hover:underline"
            >
              {getMessage('support')}
            </a> */}
          </div>
        </div>
      </div>

      <div className="flex flex-1 overflow-hidden">
        {loading && (
          <div className="absolute inset-0 flex items-center justify-center bg-white bg-opacity-75 z-50">
            <div className="text-gray-600">Loading...</div>
          </div>
        )}

        <aside
          ref={menuRef}
          className="w-[300px] overflow-y-auto pt-2 bg-bg-gray"
          style={{ height: `${height}px` }}
        >
          <BookmarkTree
            data={menu}
            selectedId={selectedMenuId}
            onNodeClick={handleNodeClick}
          />
        </aside>

        <main
          className="flex-1 overflow-y-auto p-4 bg-bg-gray"
          style={{ height: `${height}px` }}
        >
          <div className="max-w-5xl mx-auto">
            {breadcrumb.length > 0 && (
              <div className="mb-2.5">
                <nav className="flex items-center gap-1 text-sm">
                  <button
                    onClick={() => navigate('/?pid=0')}
                    className="text-primary hover:underline"
                  >
                    {getMessage('all_bookmarks')}
                  </button>
                  {breadcrumb.map((bc, idx) => (
                    <React.Fragment key={bc.id}>
                      <span>/</span>
                      <button
                        onClick={() => navigate(`/?pid=${bc.id}`)}
                        className="text-primary hover:underline"
                      >
                        {bc.title}
                      </button>
                    </React.Fragment>
                  ))}
                </nav>
              </div>
            )}

            <div className="mb-2.5 text-right">
              <Button
                variant="primary"
                size="mini"
                onClick={handleOpenCreateFolder}
                className="rounded-full"
              >
                {getMessage('add_folder')}
              </Button>
            </div>

            {search && (
              <div className="mb-2.5 flex items-center gap-2">
                <span className="font-semibold">{getMessage('filter')}:</span>
                <span className="px-2 py-1 bg-gray-200 rounded text-sm flex items-center gap-1">
                  ID: {search}
                  <button onClick={() => setSearch(null)}>
                    <X className="w-3 h-3" />
                  </button>
                </span>
              </div>
            )}

            {filteredBookmarks.length === 0 ? (
              <div className="text-center text-gray-500 py-8">
                {getMessage('no_bookmark')}
              </div>
            ) : (
              <div className="space-y-2">
                {filteredBookmarks.map((item) => (
                  <div
                    key={item.id}
                    className="flex items-center justify-between p-2 hover:bg-gray-50 rounded"
                  >
                    <div
                      className="flex-1 cursor-pointer"
                      onClick={() => handleVisit(item)}
                    >
                      <div className="flex items-center gap-2">
                        {item.url ? (
                          <Tag className="w-4 h-4 text-gray-600" />
                        ) : (
                          <Folder className="w-4 h-4 text-gray-600" />
                        )}
                        <span className="text-sm font-semibold">{item.title}</span>
                      </div>
                      {item.url && (
                        <div className="text-xs text-gray-500 mt-1 ml-6">
                          {item.url}
                        </div>
                      )}
                    </div>
                    <div className="flex gap-2">
                      <Button
                        variant="primary"
                        size="mini"
                        circle
                        plain
                        onClick={() => handleEdit(item)}
                        icon={<Edit className="w-3 h-3" />}
                      />
                      <Button
                        variant="danger"
                        size="mini"
                        circle
                        plain
                        onClick={() => handleRemove(item)}
                        icon={<Trash2 className="w-3 h-3" />}
                      />
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </main>
      </div>

      <Dialog open={dialogFormVisible} onOpenChange={setDialogFormVisible}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{getMessage('edit_bookmark')}</DialogTitle>
          </DialogHeader>
          {saving ? (
            <div className="py-8 text-center">Saving...</div>
          ) : (
            <>
              <div className="space-y-4 py-4">
                <div>
                  <label className="text-sm font-medium mb-2 block">
                    {getMessage('title')}
                  </label>
                  <Input
                    value={bookmarkData.title || ''}
                    onChange={(e) =>
                      setBookmarkData({ ...bookmarkData, title: e.target.value })
                    }
                  />
                </div>
                <div>
                  <label className="text-sm font-medium mb-2 block">
                    {getMessage('url')}
                  </label>
                  <Input
                    value={bookmarkData.url || ''}
                    onChange={(e) =>
                      setBookmarkData({ ...bookmarkData, url: e.target.value })
                    }
                  />
                </div>
                <div>
                  <label className="text-sm font-medium mb-2 block">
                    {getMessage('save_at')}
                  </label>
                  {menuSelector && (
                    <div className="mb-3">
                      <span className="px-2 py-1 bg-gray-200 rounded text-sm">
                        {menuSelector.label}
                      </span>
                    </div>
                  )}
                  <div className="border rounded p-2 max-h-[200px] overflow-y-auto">
                    <BookmarkTree
                      data={menu}
                      selectedId={menuSelector?.id}
                      onNodeClick={handleFormNodeClick}
                    />
                  </div>
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={handleCancelDialog}>
                  {getMessage('cancel_btn')}
                </Button>
                <Button variant="primary" onClick={handleConfirmDialog}>
                  {getMessage('confirm_btn')}
                </Button>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>

      <Dialog
        open={dialogAddFolderFormVisible}
        onOpenChange={setDialogAddFolderFormVisible}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{getMessage('add_folder')}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <label className="text-sm font-medium mb-2 block">目录名</label>
              <Input
                value={bookmarkFolder.title || ''}
                onChange={(e) =>
                  setBookmarkFolder({ ...bookmarkFolder, title: e.target.value })
                }
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="primary" onClick={handleCreateFolder}>
              创建
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <AlertDialog open={removeDialogOpen} onOpenChange={setRemoveDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{getMessage('notification')}</AlertDialogTitle>
            <AlertDialogDescription>
              {getMessage('confirm_remove_info')}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{getMessage('cancel_btn')}</AlertDialogCancel>
            <AlertDialogAction onClick={confirmRemove}>
              {getMessage('confirm_btn')}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

// src/bookmark/App.vue
<template>
  <el-container>
    <el-header ref="top" class="header">
      <el-row>
        <el-col :span="8">
          <div class="header_title">{{ 'appname' | lang }}</div>
        </el-col>
        <el-col :span="8">
          <!--<el-input placeholder="请输入内容" v-model="searchKey" class="input-with-select">
            <el-button slot="append" icon="el-icon-search"></el-button>
          </el-input>-->
        </el-col>
        <el-col :offset="10" :span="6" class="support">
          <el-link type="info" href="https://akawa.ink/donate" icon="el-icon-thumb" target="_blank">{{ 'donate' | lang }}</el-link>
          <el-link type="info" href="https://github.com/ety001/bookmark-extension" icon="el-icon-position" target="_blank">{{ 'source_code' | lang }}</el-link>
          <el-link type="info" href="https://creatorsdaily.com/9999e88d-0b00-46dc-8ff1-e1d311695324#comments" icon="el-icon-bangzhu" target="_blank">{{
            'support' | lang
          }}</el-link>
        </el-col>
      </el-row>
    </el-header>
    <el-container v-loading="loading">
      <el-aside width="300px" ref="menu" :style="{ height: height + 'px' }">
        <el-tree
          :empty-text="'no_bookmark' | lang"
          ref="menuTree"
          :data="menu"
          node-key="id"
          :default-expand-all="true"
          :expand-on-click-node="false"
          :highlight-current="true"
          :indent="8"
          @node-click="nodeClick"
          :draggable="false"
          :accordion="false"
        >
        </el-tree>
      </el-aside>
      <el-main :style="{ height: height + 'px' }">
        <el-row>
          <el-col :span="20" :offset="2" v-if="breadcrumb !== []" style="margin-bottom: 10px;">
            <el-breadcrumb separator="/">
              <el-breadcrumb-item :to="{ path: '/' }">{{ 'all_bookmarks' | lang }}</el-breadcrumb-item>
              <el-breadcrumb-item v-for="(bc, idx) in breadcrumb" :key="idx" :to="{ path: '/', query: { pid: bc.id } }">{{ bc.title }}</el-breadcrumb-item>
            </el-breadcrumb>
          </el-col>
          <el-col :span="20" :offset="2" style="margin-bottom: 10px; text-align: right;">
            <el-button type="primary" round size="mini" @click="openCreateFolder">{{ 'add_folder' | lang }}</el-button>
          </el-col>
          <el-col :span="20" :offset="2" v-if="search !== null">
            <span style="font-weight: 600;">{{ 'filter' | lang }}:</span>
            <el-tag closable type="info" @close="tagClose"> ID: {{ search }} </el-tag>
          </el-col>
          <el-col :span="20" :offset="2">
            <el-table
              v-if="bookmarks"
              :show-header="false"
              :empty-text="'no_bookmark' | lang"
              ref="table1"
              :data="bookmarks.filter(data => !search || data.id.includes(search))"
              style="width: 100%"
            >
              <el-table-column property="title">
                <template slot-scope="scope">
                  <el-row v-if="scope.row.url === null">
                    <el-col :span="24">
                      <div class="bm_title" @click="visit(scope.row)">
                        <i v-if="scope.row.url" class="el-icon-collection-tag"></i>
                        <i v-if="scope.row.url === null" class="el-icon-folder"></i>
                        {{ scope.row.title }}
                      </div>
                    </el-col>
                  </el-row>
                  <el-row v-else>
                    <el-col :span="24">
                      <div class="bm_title" @click="visit(scope.row)">
                        <i class="el-icon-collection-tag"></i>
                        {{ scope.row.title }}
                      </div>
                      <div class="bm_url" @click="visit(scope.row)">{{ scope.row.url }}</div>
                    </el-col>
                  </el-row>
                </template>
              </el-table-column>
              <el-table-column width="160">
                <template slot-scope="scope">
                  <el-button type="primary" @click="edit(scope.row)" icon="el-icon-edit" circle plain size="mini"></el-button>
                  <el-button type="danger" @click="remove(scope.row)" icon="el-icon-delete" circle plain size="mini"></el-button>
                </template>
              </el-table-column>
            </el-table>
          </el-col>
        </el-row>
      </el-main>
    </el-container>
    <el-dialog :show-close="false" :close-on-click-modal="false" :close-on-press-escape="false" :title="'edit_bookmark' | lang" :visible.sync="dialogFormVisible">
      <el-form ref="form1" :model="bookmarkData" v-loading="saving">
        <el-form-item :label="'title' | lang">
          <el-input v-model="bookmarkData.title"></el-input>
        </el-form-item>
        <el-form-item :label="'url' | lang">
          <el-input v-model="bookmarkData.url"></el-input>
        </el-form-item>
        <el-form-item :label="'save_at' | lang">
          <div class="menu-selector-path" v-if="menuSelector !== null">
            <el-tag>{{ menuSelector.label }}</el-tag>
          </div>
          <div class="menu-selector">
            <el-tree ref="menuTreeSelector" :data="menu" @node-click="formNodeClick" node-key="id"></el-tree>
          </div>
        </el-form-item>
      </el-form>
      <div slot="footer" class="dialog-footer">
        <el-button @click="cancelDialog">{{ 'cancel_btn' | lang }}</el-button>
        <el-button type="primary" @click="confirmDialog">{{ 'confirm_btn' | lang }}</el-button>
      </div>
    </el-dialog>
    <el-dialog :show-close="false" :close-on-click-modal="false" :close-on-press-escape="false" :title="'add_folder' | lang" :visible.sync="dialogAddFolderFormVisible">
      <el-form :model="bookmarkFolder">
        <el-form-item label="目录名">
          <el-input v-model="bookmarkFolder.title"></el-input>
        </el-form-item>
      </el-form>
      <div slot="footer" class="dialog-footer">
        <el-button type="primary" @click="createFolder">创建</el-button>
      </div>
    </el-dialog>
  </el-container>
</template>

<script>
export default {
  data() {
    return {
      port: null,
      menu: [],
      defaultProps: {
        children: 'children',
        label: 'label',
      },
      loading: false,
      height: 0,
      pid: '0',
      bid: '0',
      bookmarks: null,
      searchKey: null,
      search: null,
      breadcrumb: [],
      saving: false,
      dialogFormVisible: false,
      bookmarkData: {
        id: null,
        title: null,
        url: null,
      },
      menuSelector: null,
      dialogAddFolderFormVisible: false,
      bookmarkFolder: {
        parentId: null,
        title: null,
        url: null,
      },
    };
  },
  methods: {
    getLang(val) {
      if (!val) return '';
      return chrome.i18n.getMessage(val);
    },
    nodeClick(node) {
      this.visit(node);
    },
    formNodeClick(data, node, current) {
      this.menuSelector = data;
    },
    getBookmarkMenu() {
      this.loading = true;
      this.port.postMessage({ ctype: 'getbookmark_menu', cdata: false });
    },
    getBookmarkChildren(id) {
      if (id === null) id = 0;
      this.port.postMessage({ ctype: 'getbookmark_children', cdata: id });
    },
    visit(data) {
      if (data.url) {
        window.open(data.url);
      } else {
        this.$router.push({ path: '/', query: { pid: data.id } }).catch(e => console.log('router error:', e));
      }
    },
    edit(data) {
      this.port.postMessage({ ctype: 'getbookmark_byid', cdata: { id: data.id, action: 'edit_open' } });
    },
    editOpen(bookmark) {
      this.bookmarkData = bookmark;
      this.dialogFormVisible = true;
      this.menuSelector = {
        id: bookmark.parent.id,
        label: bookmark.parent.title,
      };
    },
    cancelDialog() {
      if (this.saving === true) return;
      this.dialogFormVisible = false;
      this.bookmarkData = {
        id: null,
        title: null,
        url: null,
      };
      this.menuSelector = null;
    },
    confirmDialog() {
      // if (this.menuSelector === null) {
      //   return this.$message({
      //     showClose: true,
      //     message: this.getLang('there_is_no_menu_selector'),
      //     type: 'error'
      //   });
      // }
      // if (this.bookmarkData.url === '' || this.bookmarkData.url === undefined) {
      //   return this.$message({
      //     showClose: true,
      //     message: this.getLang('there_is_no_url'),
      //     type: 'error',
      //   });
      // }

      this.port.postMessage({
        ctype: 'update_bookmark',
        cdata: {
          id: this.bookmarkData.id,
          title: this.bookmarkData.title,
          url: this.bookmarkData.url,
          parentId: this.menuSelector === null ? null : this.menuSelector.id,
          index: 0,
        },
      });
      this.saving = true;
    },
    remove(data) {
      const confirmInfoMsg = chrome.i18n.getMessage('confirm_remove_info');
      const confirmTitleMsg = chrome.i18n.getMessage('notification');
      const confirmBtnMsg = chrome.i18n.getMessage('confirm_btn');
      const cancelBtnMsg = chrome.i18n.getMessage('cancel_btn');
      this.$confirm(confirmInfoMsg, confirmTitleMsg, {
        confirmButtonText: confirmBtnMsg,
        cancelButtonText: cancelBtnMsg,
        type: 'warning',
      })
        .then(() => {
          this.port.postMessage({ ctype: 'remove_bookmark', cdata: data });
        })
        .catch(() => {
          // cancel
        });
    },
    tagClose() {
      this.search = null;
    },
    getBreadcrumb(id) {
      this.port.postMessage({ ctype: 'getbookmark_breadcrumb', cdata: id });
    },
    openCreateFolder() {
      this.dialogAddFolderFormVisible = true;
      this.bookmarkFolder.parentId = this.pid;
    },
    createFolder() {
      this.port.postMessage({ ctype: 'create_bookmark_folder', cdata: this.bookmarkFolder });
    },
  },
  filters: {
    lang(val) {
      if (!val) return '';
      return chrome.i18n.getMessage(val);
    },
  },
  watch: {
    $route(to, from) {
      const query = to.query;
      this.pid = query.pid === undefined ? '0' : query.pid;
      this.bid = query.bid === undefined ? '0' : query.bid;
      this.$refs.menuTree.setCurrentKey(this.pid);
      this.getBookmarkChildren(this.pid);
    },
    bid(val) {
      if (val === '0') {
        this.search = null;
      }
    },
  },
  created() {
    const successMsg = chrome.i18n.getMessage('success');
    const query = this.$route.query;
    this.pid = query.pid === undefined ? '0' : query.pid;
    this.bid = query.bid === undefined ? '0' : query.bid;
    // 与 background.js 通信
    this.port = chrome.runtime.connect({ name: 'bookmark_manager_ety001' });
    this.port.onMessage.addListener(msg => {
      switch (msg.ctype) {
        case 'getbookmark_menu':
          this.loading = false;
          this.menu = msg.cdata;
          this.$refs.menuTree.setCurrentKey(this.pid);
          this.getBookmarkChildren(this.pid);
          break;
        case 'getbookmark_children':
          const tmp = [];
          for (let i in msg.cdata) {
            tmp.push({
              id: msg.cdata[i].id,
              title: msg.cdata[i].title,
              url: msg.cdata[i].url === undefined ? null : msg.cdata[i].url,
            });
          }
          this.bookmarks = tmp;
          if (this.bid !== '0') {
            this.search = this.bid;
          }
          this.getBreadcrumb(this.pid);
          break;
        case 'remove_bookmark':
          this.$message({
            type: 'success',
            message: successMsg,
          });
          this.getBookmarkChildren(this.pid);
          break;
        case 'getbookmark_breadcrumb':
          this.breadcrumb = msg.cdata;
          break;
        case 'update_bookmark':
          this.$message({
            type: 'success',
            message: successMsg,
          });
          this.getBookmarkMenu();
          this.menuSelector = null;
          this.saving = false;
          this.dialogFormVisible = false;
          break;
        case 'getbookmark_byid':
          switch (msg.cdata.action) {
            case 'edit_open':
              this.editOpen(msg.cdata.bookmark);
              break;
          }
          break;
        case 'create_bookmark_folder':
          this.$message({
            type: 'success',
            message: successMsg,
          });
          this.getBookmarkMenu();
          this.saving = false;
          this.dialogAddFolderFormVisible = false;
          this.bookmarkFolder = {
            parentId: null,
            title: null,
            url: null,
          };
          break;
      }
    });
    // 设置网页标题
    document.title = chrome.i18n.getMessage('appname');
    // 获取书签目录
    this.getBookmarkMenu();
  },
  updated() {
    // 设置高度
    const totalHeight = document.body.offsetHeight;
    const topHeight = this.$refs.top.$vnode.elm.offsetHeight;
    this.height = totalHeight - topHeight;
  },
};
</script>

<style lang="scss" scoped>
aside {
  overflow: scroll;
  height: 100%;
  padding-top: 8px;
}
.header {
  background-color: #53a8ff;
  color: #fff;
  padding-top: 8px;
}
.header_title {
  font-size: 22px;
  font-weight: 800;
  padding-top: 8px;
  padding-left: 40px;
}
.bm_title {
  font-size: 14px;
  font-weight: 600;
}
.bm_url {
  font-size: 12px;
  font-weight: 200;
}
.support {
  text-align: right;
  padding-top: 10px;
}
.support a,
.support a:hover {
  color: #fff;
  text-decoration: none;
}
.menu-selector {
  clear: both;
  height: 200px;
  overflow-x: hidden;
  overflow-y: scroll;
}
.menu-selector-path {
  clear: both;
  margin-bottom: 14px;
}
.el-table tr {
  cursor: pointer;
}
</style>
