// src/tab/App.vue
<template>
  <div>
    <div v-if="bookmark">
      <el-row ref="top" class="top">
        <el-col :span="4" class="capital">
          <span>{{ 'appname' | lang }}</span>
        </el-col>
        <el-col :span="16">
          <el-row>
            <el-col :span="24">
              <div class="title">{{ bookmark.title }}</div>
              <el-link class="url" type="info" :href="bookmark.url" target="_blank" icon="el-icon-connection">{{ bookmark.url }}</el-link>
            </el-col>
          </el-row>
          <el-row>
            <el-col :span="24">
              <el-button type="success" @click="nextBM" icon="el-icon-right" circle plain size="small"></el-button>
              <el-button type="info" @click="block" icon="el-icon-close-notification" circle plain size="small"></el-button>
              <el-button type="primary" @click="edit" icon="el-icon-edit" circle plain size="small"></el-button>
              <el-button type="danger" @click="remove" icon="el-icon-delete" circle plain size="small"></el-button>
            </el-col>
          </el-row>
        </el-col>
        <el-col :span="4" style="padding-right: 40px; text-align: right;">
          <a href="https://creatorsdaily.com/9999e88d-0b00-46dc-8ff1-e1d311695324?utm_source=vote" target="_blank"
            ><img src="https://creatorsdaily.com/api/9999e88d-0b00-46dc-8ff1-e1d311695324/vote.svg?theme=dark"/></a
          ><br /><br />
          <el-link type="info" href="https://akawa.ink/donate" icon="el-icon-thumb" target="_blank">{{ 'donate' | lang }}</el-link>
          <el-link type="info" href="https://github.com/ety001/bookmark-extension" icon="el-icon-position" target="_blank">{{ 'source_code' | lang }}</el-link>
          <el-link type="info" href="https://creatorsdaily.com/9999e88d-0b00-46dc-8ff1-e1d311695324#comments" icon="el-icon-bangzhu" target="_blank">{{
            'support' | lang
          }}</el-link>
        </el-col>
      </el-row>
      <el-row ref="box" class="box" @click="visit" v-loading="loading">
        <el-col :span="24">
          <iframe ref="iframe1" :src="baseUrl + src" sandbox="" :style="{ height: iframeHeight + 'px' }"></iframe>
        </el-col>
      </el-row>
    </div>
    <div v-else>
      <el-row style="margin: 20px;">
        <el-col :span="8">
          <el-alert :closable="false" :title="'no_bookmark' | lang" type="error"></el-alert>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      port: null,
      bookmark: null,
      config: null,
      src: null,
      baseUrl: '',
      iframeHeight: 0,
      loading: false,
    };
  },
  methods: {
    nextBM() {
      this.getBookmark();
    },
    block() {
      const confirmInfoMsg = chrome.i18n.getMessage('confirm_block_info');
      const confirmTitleMsg = chrome.i18n.getMessage('notification');
      const confirmBtnMsg = chrome.i18n.getMessage('confirm_btn');
      const cancelBtnMsg = chrome.i18n.getMessage('cancel_btn');
      this.$confirm(confirmInfoMsg, confirmTitleMsg, {
        confirmButtonText: confirmBtnMsg,
        cancelButtonText: cancelBtnMsg,
        type: 'warning',
      })
        .then(() => {
          this.port.postMessage({ ctype: 'block', cdata: this.bookmark });
        })
        .catch(() => {
          // cancel
        });
    },
    visit() {
      window.open(this.src);
    },
    edit() {
      const baseUrl = chrome.runtime.getURL('bookmark/bookmark.html#/');
      const url = `${baseUrl}?pid=${this.bookmark.parentId}&bid=${this.bookmark.id}`;
      window.open(url);
    },
    remove() {
      const confirmInfoMsg = chrome.i18n.getMessage('confirm_remove_info');
      const confirmTitleMsg = chrome.i18n.getMessage('notification');
      const confirmBtnMsg = chrome.i18n.getMessage('confirm_btn');
      const cancelBtnMsg = chrome.i18n.getMessage('cancel_btn');
      this.$confirm(confirmInfoMsg, confirmTitleMsg, {
        confirmButtonText: confirmBtnMsg,
        cancelButtonText: cancelBtnMsg,
        type: 'warning',
      })
        .then(() => {
          this.port.postMessage({ ctype: 'remove_bookmark', cdata: this.bookmark });
        })
        .catch(() => {
          // cancel
        });
    },
    getLang(val) {
      if (!val) return '';
      return chrome.i18n.getMessage(val);
    },
    getBookmark() {
      // 获取书签
      this.loading = true;
      this.port.postMessage({ ctype: 'getbookmark_from_full', cdata: false });
    },
  },
  filters: {
    lang(val) {
      if (!val) return '';
      return chrome.i18n.getMessage(val);
    },
  },
  created() {
    const successMsg = chrome.i18n.getMessage('success');
    // 与 background.js 通信
    this.port = chrome.runtime.connect({ name: 'bookmark_manager_ety001' });
    this.port.onMessage.addListener(msg => {
      switch (msg.ctype) {
        case 'getbookmark_from_full':
          if (msg.cdata === null) return;
          this.bookmark = msg.cdata;
          this.src = this.bookmark.url;
          break;
        case 'remove_bookmark':
          this.$message({
            type: 'success',
            message: successMsg,
          });
          this.getBookmark();
          break;
        case 'block':
          this.$message({
            type: 'success',
            message: successMsg,
          });
          this.getBookmark();
          break;
      }
    });
    // 获取书签
    this.getBookmark();
    // 设置网页标题
    document.title = chrome.i18n.getMessage('appname');
  },
  updated() {
    // 设置iframe高度
    const totalHeight = document.body.offsetHeight;
    const topHeight = this.$refs.top.$vnode.elm.offsetHeight;
    this.iframeHeight = totalHeight - topHeight;
    // 设置iframe加载事件
    if (this.$refs.iframe1.onload === null) {
      this.$refs.iframe1.onload = () => {
        this.loading = false;
      };
    }
  },
};
</script>

<style lang="scss" scoped>
.top {
  background-color: #eee;
  color: #444;
  padding: 20px 0;
  border-bottom: 2px solid #ccc;
}
.top .capital {
  font-size: 24px;
  font-weight: 800;
  line-height: 20px;
  padding: 30px 0;
  text-align: center;
}
.top .title {
  font-size: 18px;
  font-weight: 500;
  margin-bottom: 8px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.top .url {
  margin-bottom: 8px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 500px;
}
.box {
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
iframe {
  border: 0;
  width: 100%;
  height: 100%;
  cursor: pointer;
}
</style>

// entrypoints/tab/App.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Button } from '../../components/ui/button';
import { Alert, AlertDescription, AlertTitle } from '../../components/ui/alert';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '../../components/ui/alert-dialog';
import { useToast } from '../../components/ui/use-toast';
import { getMessage } from '../../utils/i18n';
import { ArrowRight, X, Edit, Trash2, BellOff, ExternalLink } from 'lucide-react';
import type { Bookmark } from '../../store';

export default function App() {
  const { toast } = useToast();
  const [bookmark, setBookmark] = useState<Bookmark | null>(null);
  const [loading, setLoading] = useState(false);
  const [blockDialogOpen, setBlockDialogOpen] = useState(false);
  const [removeDialogOpen, setRemoveDialogOpen] = useState(false);
  const topRef = useRef<HTMLDivElement>(null);
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [iframeHeight, setIframeHeight] = useState(0);

  useEffect(() => {
    document.title = getMessage('appname');
    getBookmark();
  }, []);

  useEffect(() => {
    if (topRef.current && iframeRef.current) {
      const totalHeight = document.body.offsetHeight;
      const topHeight = topRef.current.offsetHeight;
      setIframeHeight(totalHeight - topHeight);
    }
  }, [bookmark]);

  const getBookmark = () => {
    setLoading(true);
    chrome.runtime.sendMessage(
      { ctype: 'getbookmark_from_full', cdata: false },
      (response) => {
        if (response && response.cdata) {
          setBookmark(response.cdata);
          setLoading(false);
        } else {
          setLoading(false);
        }
      }
    );
  };

  const handleBlock = () => {
    setBlockDialogOpen(true);
  };

  const confirmBlock = () => {
    if (!bookmark) return;
    chrome.runtime.sendMessage(
      { ctype: 'block', cdata: bookmark },
      (response) => {
        if (response && response.cdata) {
          toast({
            variant: 'success',
            title: getMessage('success'),
          });
          getBookmark();
        }
      }
    );
    setBlockDialogOpen(false);
  };

  const handleRemove = () => {
    setRemoveDialogOpen(true);
  };

  const confirmRemove = () => {
    if (!bookmark) return;
    chrome.runtime.sendMessage(
      { ctype: 'remove_bookmark', cdata: bookmark },
      (response) => {
        if (response && response.cdata) {
          toast({
            variant: 'success',
            title: getMessage('success'),
          });
          getBookmark();
        }
      }
    );
    setRemoveDialogOpen(false);
  };

  const handleEdit = () => {
    if (!bookmark) return;
    const baseUrl = chrome.runtime.getURL('bookmark/bookmark.html#/');
    const url = `${baseUrl}?pid=${bookmark.parentId}&bid=${bookmark.id}`;
    window.open(url);
  };

  const handleVisit = () => {
    if (bookmark?.url) {
      window.open(bookmark.url);
    }
  };

  const handleIframeLoad = () => {
    setLoading(false);
  };

  if (!bookmark) {
    return (
      <div className="m-5">
        <Alert variant="error">
          <AlertTitle>{getMessage('no_bookmark')}</AlertTitle>
        </Alert>
      </div>
    );
  }

  return (
    <div className="h-screen flex flex-col">
      <div
        ref={topRef}
        className="bg-[#eee] text-[#444] py-5 border-b-2 border-[#ccc]"
      >
        <div className="flex items-start">
          <div className="w-1/6 flex justify-center items-center py-8">
            <span className="text-[24px] font-extrabold leading-5">
              {getMessage('appname')}
            </span>
          </div>
          <div className="flex-1 px-4">
            <div className="mb-2">
              <div className="text-[18px] font-medium mb-2 overflow-hidden text-ellipsis whitespace-nowrap">
                {bookmark.title}
              </div>
              <a
                href={bookmark.url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-sm text-gray-600 mb-2 overflow-hidden text-ellipsis whitespace-nowrap max-w-[500px] block hover:underline"
              >
                {bookmark.url}
              </a>
            </div>
            <div className="flex gap-2">
              <Button
                variant="success"
                size="small"
                circle
                plain
                onClick={getBookmark}
                icon={<ArrowRight className="w-4 h-4" />}
              />
              <Button
                variant="info"
                size="small"
                circle
                plain
                onClick={handleBlock}
                icon={<BellOff className="w-4 h-4" />}
              />
              <Button
                variant="primary"
                size="small"
                circle
                plain
                onClick={handleEdit}
                icon={<Edit className="w-4 h-4" />}
              />
              <Button
                variant="danger"
                size="small"
                circle
                plain
                onClick={handleRemove}
                icon={<Trash2 className="w-4 h-4" />}
              />
            </div>
          </div>
          <div className="w-1/6 pr-10 text-right">
            {/* TODO: 推广页面已不存在，暂时注释掉 */}
            {/* <a
              href="https://creatorsdaily.com/9999e88d-0b00-46dc-8ff1-e1d311695324?utm_source=vote"
              target="_blank"
              rel="noopener noreferrer"
            >
              <img
                src="https://creatorsdaily.com/api/9999e88d-0b00-46dc-8ff1-e1d311695324/vote.svg?theme=dark"
                alt="vote"
              />
            </a>
            <br />
            <br /> */}
            <div className="flex flex-col gap-2">
              <a
                href="https://akawa.ink/donate"
                target="_blank"
                rel="noopener noreferrer"
                className="text-sm text-gray-600 hover:underline"
              >
                {getMessage('donate')}
              </a>
              <a
                href="https://github.com/ety001/bookmark-extension"
                target="_blank"
                rel="noopener noreferrer"
                className="text-sm text-gray-600 hover:underline"
              >
                {getMessage('source_code')}
              </a>
              {/* TODO: 推广页面已不存在，暂时注释掉 */}
              {/* <a
                href="https://creatorsdaily.com/9999e88d-0b00-46dc-8ff1-e1d311695324#comments"
                target="_blank"
                rel="noopener noreferrer"
                className="text-sm text-gray-600 hover:underline"
              >
                {getMessage('support')}
              </a> */}
            </div>
          </div>
        </div>
      </div>
      <div
        className="flex-1 relative cursor-pointer"
        onClick={handleVisit}
      >
        {loading && (
          <div className="absolute inset-0 flex items-center justify-center bg-white bg-opacity-75 z-10">
            <div className="text-gray-600">Loading...</div>
          </div>
        )}
        <iframe
          ref={iframeRef}
          src={bookmark.url}
          sandbox=""
          className="w-full h-full border-0"
          style={{ height: `${iframeHeight}px` }}
          onLoad={handleIframeLoad}
        />
      </div>

      <AlertDialog open={blockDialogOpen} onOpenChange={setBlockDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{getMessage('notification')}</AlertDialogTitle>
            <AlertDialogDescription>
              {getMessage('confirm_block_info')}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{getMessage('cancel_btn')}</AlertDialogCancel>
            <AlertDialogAction onClick={confirmBlock}>
              {getMessage('confirm_btn')}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <AlertDialog open={removeDialogOpen} onOpenChange={setRemoveDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{getMessage('notification')}</AlertDialogTitle>
            <AlertDialogDescription>
              {getMessage('confirm_remove_info')}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{getMessage('cancel_btn')}</AlertDialogCancel>
            <AlertDialogAction onClick={confirmRemove}>
              {getMessage('confirm_btn')}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
